language: cpp
dist: bionic
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: COMPILER=gcc GCC=7 
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-6.0
          packages:
            - clang-6.0
      env: COMPILER=clang CLANG=6.0
env:
  global:
        - POUTRE_CMAKE_EXTRA_ARGS="-DBUILD_PYTHON=ON -DCMAKE_BUILD_TYPE=Release" 
        #- POUTRE_CMAKE_GENERATOR="Ninja"
before_install:
    - sudo apt-get update
    # Boost and ninja build
    - sudo apt-get install -qq libboost-dev-all ninja-build
    # cppcheck
    - sudo apt-get install -qq cppcheck
    #doc
    - sudo apt-get install -qq doxygen graphviz
    #coverage
    - sudo pip install codecov
    - |
      # Configure build variables
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        if [[ "$COMPILER" == "gcc" ]]; then
          export CXX=g++-$GCC CC=gcc-$GCC;
        fi
        if [[ "$COMPILER" == "clang" ]]; then
          export CXX=clang++-$CLANG CC=clang-$CLANG;
        fi
      fi
script:
  - mkdir -p build
  - cd build
  #- cmake -GNinja "$POUTRE_CMAKE_EXTRA_ARGS" -DBUILD_SHARED_LIBS=ON -DBUILD_TEST=ON $POUTRE_CMAKE_EXTRA_ARGS ..
  - cmake "$POUTRE_CMAKE_EXTRA_ARGS" -DBUILD_SHARED_LIBS=ON -DBUILD_TEST=ON $POUTRE_CMAKE_EXTRA_ARGS ..
  - cmake --build . --config Release
  - ctest . -C Release --output-on-failure
  # cppcheck
  #- cppcheck --quiet --error-exitcode=1 . 
  - cppcheck --quiet . 
# see https://github.com/richelbilderbeek/travis_cpp_tutorial/blob/master/travis_cpp_tutorial.pdf
#after_success:
#  - bash <(curl -s https://codecov.io/bash)