language: cpp
dist: focal

env:
  global:
    - /usr/local/bin:$PATH

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          packages:
            - lcov
      env: COMPILER=g++ C_COMPILER=gcc BUILD_TYPE=Coverage

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-focal-10.0
          packages:
            - clang-10.0
      env: COMPILER=clang CLANG=10.0
env:
  global:
        - POUTRE_CMAKE_EXTRA_ARGS="-DBUILD_PYTHON=ON -DCMAKE_BUILD_TYPE=Release" 
        #- POUTRE_CMAKE_GENERATOR="Ninja"
before_install:
    - sudo apt-get update
    # Boost and ninja build
    - sudo apt-get install -qq libboost-all-dev ninja-build
    # cppcheck
    - sudo apt-get install -qq cppcheck
    #doc
    - sudo apt-get install -qq doxygen graphviz
    - |
      # Configure build variables
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        if [[ "$COMPILER" == "gcc" ]]; then
          export CXX=g++-$GCC CC=gcc-$GCC;
        fi
        if [[ "$COMPILER" == "clang" ]]; then
          export CXX=clang++-$CLANG CC=clang-$CLANG;
        fi
      fi
install:
  - if [ "${BUILD_TYPE}" == "Coverage" -a "${TRAVIS_OS_NAME}" == "linux" ]; then
      PATH=~/.local/bin:${PATH};
      pip install --user --upgrade pip;
      travis_wait pip install --user cpp-coveralls;
    fi
script:
  - mkdir -p build
  - cd build
  - cmake "$POUTRE_CMAKE_EXTRA_ARGS" -DBUILD_SHARED_LIBS=ON -DBUILD_TEST=ON -DBUILD_BENCH=ON $POUTRE_CMAKE_EXTRA_ARGS ..
  - cmake --build . --config Release
  - ctest . -C Release --output-on-failure
  # cppcheck
  - cppcheck -f --std=c++11 --inline-suppr -i build -i thirdparties --quiet --error-exitcode=1 .
# see https://github.com/richelbilderbeek/travis_cpp_tutorial/blob/master/travis_cpp_tutorial.pdf
#after_success:
#  - bash <(curl -s https://codecov.io/bash)
after_success:
  - if [ "${BUILD_TYPE}" == "Coverage" -a "${TRAVIS_OS_NAME}" == "linux" ]; then
      coveralls --include src --include include --gcov-options '\-lp' --root .. --build-root .;
    fi
